title:            aadm.github.io
description:      Things I want to remember. And some photographs too.
logo:
disqus_shortname:
search:           true
#Change url to your domain. Leave localhost server or blank when working locally.
url:

# Owner/author information
owner:
  name:           Alessandro Amato del Monte
  avatar:
  email:          alessandro.adm@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        aadmtwi
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:      aadm
  flickr:         aadm
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+AlessandroAmatodelMonte

# Analytics and webmaster tools stuff goes here
google_analytics:   'UA-32354823-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: index.html
  - title: About
    url: about.html
  - title: Archive
    url: archive.html
  - title: Tags
    url: tags.html
  - title: Projects
    url: projects.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year-:month-:day-:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# markdown:      redcarpet
# redcarpet:
#   extensions: ["smart","tables", "no_intra_emphasis", "autolink"]



# flickr_set:
#   gallery_tag:   'p'
#   gallery_class: 'gallery'
#   a_href:        nil
#   a_target:      '_blank'
#   image_rel:     ''
#   image_size:    'l'
#   api_key:       '8105bdb9c28f61b889b7dca33d71cf8d'


# gallery:
#   # path to the gallery
#   dir: images
#   # title for gallery index
#   title: "Photos"
#   # title prefix for gallery page. title=title_prefix+gallery_name
#   title_prefix: "Photos: "
#   # field to control sorting of galleries for the index page
#   # (possible values are: title, date_time, best_image)
#   sort_field: "date_time"
#   # sizes for thumbnails
#   thumbnail_size:
#     x: 400
#     y: 400
#   # custom configuration for individual gallery
#   # best_image is image for the index page (defaults to last image)
#   galleries:
#     parma:
#       best_image: 20130413_AA02274.NEF.jpg

